export const powerType = {
  AC_1_PHASE: 'AC_1_PHASE',
  AC_2_PHASE: ' AC_2_PHASE',
  AC_2_PHASE_SPLIT: 'AC_2_PHASE_SPLIT',
  AC_3_PHASE: ' AC_3_PHASE',
  DC: 'DC'
};
export const connectorType = {
  CHADEMO: 'CHADEMO',
  CHAOJI: 'CHAOJI',
  DOMESTIC_A: 'DOMESTIC_A',
  DOMESTIC_B: 'DOMESTIC_B',
  DOMESTIC_C: 'DOMESTIC_C',
  DOMESTIC_D: 'DOMESTIC_D',
  DOMESTIC_E: 'DOMESTIC_E',
  DOMESTIC_F: 'DOMESTIC_F',
  DOMESTIC_G: 'DOMESTIC_G',
  DOMESTIC_H: 'DOMESTIC_H',
  DOMESTIC_I: 'DOMESTIC_I',
  DOMESTIC_J: 'DOMESTIC_J',
  DOMESTIC_K: 'DOMESTIC_K',
  DOMESTIC_L: 'DOMESTIC_L',
  DOMESTIC_M: 'DOMESTIC_M',
  DOMESTIC_N: 'DOMESTIC_N',
  DOMESTIC_O: 'DOMESTIC_O',
  GBT_AC: 'GBT_AC',
  GBT_DC: 'GBT_DC',
  IEC_60309_2_single_16: 'IEC_60309_2_single_16',
  IEC_60309_2_three_16: 'IEC_60309_2_three_16'
};
export const StatusSchedule = {
  period_begin: 'period_begin',
  period_end: 'period_end',
  status: 'status'
};
export const ConnectorFormat = {
  SOCKET: 'SOCKET',
  CABLE: 'CABLE'
};
export const Status = {
  AVAILABLE: 'AVAILABLE',
  BLOCKED: 'BLOCKED'
};
export const facility = {
  HOTEL: 'HOTEL',
  RESTAURANT: ' RESTAURANT',
  CAFE: 'CAFE',
  MALL: 'MALL',
  SUPERMARKET: 'SUPERMARKET',
  SPORT: 'SPORT',
  RECREATION_AREA: ' RECREATION_AREA',
  NATURE: 'NATURE',
  MUSEUM: 'MUSEUM',
  BIKE_SHARING: ' BIKE_SHARING',
  BUS_STOP: 'BUS_STOP',
  TAXI_STAND: 'TAXI_STAND',
  TRAM_STOP: 'TRAM_STOP',
  METRO_STATION: ' METRO_STATION',
  TRAIN_STATION: ' TRAIN_STATION',
  AIRPORT: 'AIRPORT',
  PARKING_LOT: 'PARKING_LOT',
  CARPOOL_PARKING: '  CARPOOL_PARKING',
  FUEL_STATION: 'FUEL_STATION',
  WIFI: 'WIFI'
};
export const connectorFormat = {
  SOCKET: 'SOCKET',
  CABLE: 'CABLE'
};
export const imageCategory = {
  CHARGER: 'CHARGER',
  ENTRANCE: 'ENTRANCE',
  LOCATION: 'LOCATION',
  NETWORK: 'NETWORK',
  OPERATOR: 'OPERATOR',
  OTHER: 'OTHER',
  OWNER: 'OWNER'
};
export const parkingRestriction = {
  EV_ONLY: 'EV_ONLY',
  PLUGGED: 'PLUGGED',
  DISABLED: 'DISABLED',
  CUTOMERS: 'CUSTOMERS',
  MOTORCYCLES: 'MOTORCYCLES'
};
export const parkingType = {
  ALONG_MOTORWAY: 'ALONG_MOTORWAY',
  PARKING_GARAGE: ' PARKING_GARAGE',
  PARKING_LOT: ' PARKING_LOT',
  ON_DRIVEWAY: ' ON_DRIVEWAY',
  ON_STREET: 'ON_STREET',
  UNDERGROUND_GARAGE: 'UNDERGROUND_GARAGE'
};
export const capability = {
  CHARGING_PROFILE_CAPABLE: 'CHARGING_PROFILE_CAPABLE',
  CHARGING_PREFERENCES_CAPABLE: ' CHARGING_PREFERENCES_CAPABLE',
  CHIP_CARD_SUPPORT: ' CHIP_CARD_SUPPORT',
  CONTACTLESS_CARD_SUPPORT: ' CONTACTLESS_CARD_SUPPORT',
  CREDIT_CARD_PAYABLE: 'CREDIT_CARD_PAYABLE',
  DEBIT_CARD_PAYABLE: 'DEBIT_CARD_PAYABLE',
  PED_TERMINAL: 'PED_TERMINAL',
  REMOTE_START_STOP_CAPABLE: '  REMOTE_START_STOP_CAPABLE',
  RESERVABLE: ' RESERVABLE',
  RFID_READER: '  RFID_READER',
  START_SESSION_CONNECTOR_REQUIRED: '   START_SESSION_CONNECTOR_REQUIRED',
  TOKEN_GROUP_CAPABLE: ' TOKEN_GROUP_CAPABLE',
  UNLOCK_CAPABLE: 'UNLOCK_CAPABLE'
};
export const tokenType = {
  AD_HOC_USER: 'ADD_HOC_USER',
  APP_USER: 'APP_USER',
  OTHER: 'OTHER',
  RFID: 'RFID'
};
