export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SET_SETTINGS = '[SETTINGS] SET SETTINGS';
export const CUSTOMER_POLICY_MODEL = 'CUSTOMER_POLICY_MODEL';
export const SET_DEFAULT_SETTINGS = '[SETTINGS] SET DEFAULT SETTINGS';
export const SET_INITIAL_SETTINGS = '[SETTINGS] SET INITIAL SETTINGS';
export const RESET_DEFAULT_SETTINGS = '[SETTINGS] RESET DEFAULT SETTINGS';
export const SET_GROUP_MODEL = 'SET_GROUP_MODEL';
export const SET_CHARGE_BOX_MODEL = 'SET_CHARGE_BOX_MODEL';

export const SET_USER_DATA = '[USER] SET DATA';
export const REMOVE_USER_DATA = '[USER] REMOVE DATA';
export const USER_LOGGED_OUT = '[USER] LOGGED OUT';

export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const GET_USERS = 'GET_USERS';
export const GET_TAG = 'GET_TAG';
export const GET_POLICY_TAGS = 'GET_POLICY_TAGS';
export const GET_RATES = 'GET_RATES';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_SELECTED_CUSTOMER = 'GET_SELECTED_CUSTOMER';
export const GET_USER = 'GET_USER';
export const GET_POLICIES = 'GET_POLICES';
export const GET_CHARGING_BOX = 'GET_CHARGING_BOX';
export const GET_GROUPS = 'GET_GROUPS';
export const GET_DASHBOARD = 'GET_DASHBOARD';
export const USER_GROUP = 'USER_GROUP';
export const GET_COMPANYS = 'GET_COMPANYS';
export const SELECTED_CHARGEBOX = 'SELECTED_CHARGEBOX';
export const CUSTOMER_POLICY = 'CUSTOMER_POLICY';
export const USER_BY_GROUPID = 'USER_BY_GROUPID';
export const USER_BY_EMAIL = 'USER_BY_EMAIL';

export const SET_LOADING = 'SET_LOADING';
export const NEW_CHARGE_BOX = 'NEW_CHARGE_BOX';
export const NEW_PRICING_POLICY = 'NEW_PRICING_POLICY';
export const NEW_GROUP = 'NEW_GROUP';
export const NEW_POLICY_TAGE = 'NEW_POLICY_TAGE';

export const NEW_USER_GROUP = 'NEW_USER_GROUP';
export const NEW_CONNECTOR = 'NEW_CONNECTOR';
export const NEW_COMPANY = 'NEW_COMPANY';
export const NEW_RESERVATION = 'NEW_RESERVATION';
export const NEW_RATES = 'NEW_RATES';

export const SINGLE_CHARGE_BOX = 'SINGLE_CHARGE_BOX';
export const SINGLE_GROUP = 'SINGLE_GROUP';
export const SINGLE_POLICY = 'SINGLE_POLICY';
export const SINGLE_USER_GROUP = 'SINGLE_USER_GROUP';
export const SINGLE_COMPANY = 'SINGLE_COMPANY';

export const UPDATE_GROUP = 'UPDATE_GROUP';
export const UPDATE_POLICY = 'UPDATE_POLICY';
export const UPDATE_CHARGE_BOX = 'UPDATE_CHARGE_BOX';
export const UPDATE_STATUS_GROUP = 'UPDATE_STATUS_GROUP';
export const UPDATE_USER_GROUP = 'UPDATE_USER_GROUP';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';

export const FETCH_POLICY_BY_CHARGE_BOX = 'FETCH_POLICY_BY_CHARGE_BOX';
export const FETCH_CONNECTOR_BY_CHARGE_BOX = 'FETCH_CONNECTOR_BY_CHARGE_BOX';
export const FETCH_POLICY_BY_GROUP = 'FETCH_POLICY_BY_GROUP';
export const FETCH_CHARGE_BOX_GROUP = 'FETCH_CHARGE_BOX_GROUP';
