export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SET_SETTINGS = '[SETTINGS] SET SETTINGS';
export const SET_DEFAULT_SETTINGS = '[SETTINGS] SET DEFAULT SETTINGS';
export const SET_INITIAL_SETTINGS = '[SETTINGS] SET INITIAL SETTINGS';
export const SET_STEPPER = 'SET_STEPPER';
export const SET_LOGIN_MODEL = 'SET_LOGIN_MODEL';
export const SET_PAYMENT_MODEL = 'SET_PAYMENT_MODEL';
export const RESET_DEFAULT_SETTINGS = '[SETTINGS] RESET DEFAULT SETTINGS';
export const SET_QR_READER_MODEL = 'SET_QR_READER_MODEL';
export const SET_WALK_IN_USER_MODEL = 'SET_WALK_IN_USER_MODEL';
export const SET_USER_DATA = '[USER] SET DATA';
export const REMOVE_USER_DATA = '[USER] REMOVE DATA';
export const USER_LOGGED_OUT = '[USER] LOGGED OUT';
export const SOCKET_TRIGGER = '[USER] SOCKET TRIGGER';
export const GET_CHARGE_BOX_USER = '[USER] GET CHARGE BOX USER';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const SELECTED_RESERVATION = 'SELECTED_RESERVATION';

export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const GET_POLICIES = 'GET_POLICES';
export const GET_CHARGING_BOX = 'GET_CHARGING_BOX';
export const GET_GROUPS = 'GET_GROUPS';
export const GET_DASHBOARD = 'GET_DASHBOARD';
export const USER_GROUP = 'USER_GROUP';
export const GET_COMPANYS = 'GET_COMPANYS';
export const GET_RESERVATION = 'GET_RESERVATION';
export const GET_CHARGE_BOX_INFO = 'GET_CHARGE_BOX_INFO';

export const SET_LOADING = 'SET_LOADING';
export const NEW_CHARGE_BOX = 'NEW_CHARGE_BOX';
export const NEW_PRICING_POLICY = 'NEW_PRICING_POLICY';
export const NEW_GROUP = 'NEW_GROUP';
export const NEW_USER_GROUP = 'NEW_USER_GROUP';
export const NEW_CONNECTOR = 'NEW_CONNECTOR';
export const NEW_COMPANY = 'NEW_COMPANY';
export const NEW_RESERVATION = 'NEW_RESERVATION';

export const SINGLE_CHARGE_BOX = 'SINGLE_CHARGE_BOX';
export const SINGLE_CHARGE_BOX_POLICY = 'SINGLE_CHARGE_BOX_POLICY';
export const SINGLE_CHARGE_BOX_CONNECTOR = 'SINGLE_CHARGE_BOX_CONNECTOR';
export const SINGLE_CHARGE_BOX_SELETED_CONNECTOR = 'SINGLE_CHARGE_BOX_SELETED_CONNECTOR';
export const SINGLE_GROUP = 'SINGLE_GROUP';
export const SINGLE_POLICY = 'SINGLE_POLICY';
export const SINGLE_USER_GROUP = 'SINGLE_USER_GROUP';
export const SINGLE_COMPANY = 'SINGLE_COMPANY';

export const UPDATE_GROUP = 'UPDATE_GROUP';
export const UPDATE_POLICY = 'UPDATE_POLICY';
export const UPDATE_CHARGE_BOX = 'UPDATE_CHARGE_BOX';
export const UPDATE_STATUS_GROUP = 'UPDATE_STATUS_GROUP';
export const UPDATE_USER_GROUP = 'UPDATE_USER_GROUP';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';

//Trigger
export const LOCAL_STORAGE_TRIGGER = 'LOCAL_STORAGE_TRIGGER';

//Transactions

export const START_TRANSACTION = 'START_TRANSACTION';
export const STOP_TRANSACTION = 'STOP_TRANSACTION';
export const CHECK_STATUS = 'CHECK_STATUS';
